# Site settings
title: Dan Salo
description: "Tech Lead applying AI/ML to Cybersecurity"
url: "http://dancsalo.github.io"
github_username:  dancsalo
linkedin_username: dancsalo

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Collections
collections:
  thoughts:
    output: false

# SEO
facebook:
  publisher: 768300382
social:
  name: Dan Salo
  links:
    - https://www.linkedin.com/in/dancsalo
    - https://github.com/dancsalo
webmaster_verifications:
  google: QzcN1XAcVxz0fZd1IqhqgiBkKXmYwpmHkMTdabUsxjY

# Gems
gems:
- jekyll-seo-tag
